# Generated by Django 6.0.2 on 2026-02-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
