# Generated by Django 6.0.2 on 2026-02-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_studentactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_role',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_role',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
