# Generated by Django 6.0.2 on 2026-02-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='total_marks',
            field=models.IntegerField(default=15),
        ),
    ]
