# Generated by Django 6.0.2 on 2026-02-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_certificate_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='study_time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
